"""
preprocess.py

Loads chest X-ray images from data/raw/<ClassName>/, applies preprocessing
(grayscale conversion, resizing, normalization) with OpenCV, and returns
NumPy arrays ready for model training.

This module is dataset-agnostic: it works on the synthetic sample data
generated by generate_sample_data.py or on a real dataset dropped into the
same folder structure.
"""

import os
import numpy as np
import cv2

IMG_SIZE = 128  # resized input size fed to the CNN
CLASSES = ["COVID", "NonCOVID", "Normal"]
RAW_DIR = os.path.join(os.path.dirname(__file__), "data", "raw")


def load_image(path, img_size=IMG_SIZE):
    """Load a single image, convert to grayscale, resize, normalize to [0,1]."""
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise ValueError(f"Could not read image: {path}")
    img = cv2.resize(img, (img_size, img_size), interpolation=cv2.INTER_AREA)
    img = img.astype("float32") / 255.0
    return img


def load_dataset(raw_dir=RAW_DIR, classes=CLASSES, img_size=IMG_SIZE):
    """
    Walks the class folders, loads + preprocesses every image, and returns:
        X: np.ndarray of shape (N, img_size, img_size, 1)
        y: np.ndarray of shape (N,) with integer class labels
        class_names: list mapping label index -> class name
    """
    X, y = [], []

    for label_idx, class_name in enumerate(classes):
        class_dir = os.path.join(raw_dir, class_name)
        if not os.path.isdir(class_dir):
            print(f"Warning: missing class folder '{class_dir}', skipping.")
            continue

        files = [f for f in os.listdir(class_dir) if f.lower().endswith((".png", ".jpg", ".jpeg"))]
        for fname in files:
            path = os.path.join(class_dir, fname)
            try:
                img = load_image(path, img_size)
            except ValueError as e:
                print(f"Skipping unreadable file: {e}")
                continue
            X.append(img)
            y.append(label_idx)

    if not X:
        raise RuntimeError(
            f"No images found under {raw_dir}. "
            "Run generate_sample_data.py first, or add real images to data/raw/<ClassName>/."
        )

    X = np.array(X, dtype="float32")
    X = np.expand_dims(X, axis=-1)  # add channel dimension -> (N, H, W, 1)
    y = np.array(y, dtype="int64")

    return X, y, classes


if __name__ == "__main__":
    X, y, class_names = load_dataset()
    print(f"Loaded {X.shape[0]} images, shape per image: {X.shape[1:]}")
    print(f"Classes: {class_names}")
    print(f"Class distribution: {np.bincount(y)}")
